// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnimalAge")
                        .HasColumnType("int");

                    b.Property<string>("AnimalDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("AnimalName")
                        .HasColumnType("longtext");

                    b.Property<string>("AnimalType")
                        .HasColumnType("longtext");

                    b.Property<string>("MaleFemale")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AnimalAge = 3,
                            AnimalDescription = "They were found dumpster diving.",
                            AnimalName = "Trash",
                            AnimalType = "Dog",
                            MaleFemale = "Female"
                        },
                        new
                        {
                            AnimalId = 2,
                            AnimalAge = 5,
                            AnimalDescription = "Likes to do your taxes.",
                            AnimalName = "Nerd",
                            AnimalType = "Dog",
                            MaleFemale = "Male"
                        },
                        new
                        {
                            AnimalId = 3,
                            AnimalAge = 20,
                            AnimalDescription = "They are the Illuminati. Don't cross them or you'll be swimming with the fishes.",
                            AnimalName = "Illuminati",
                            AnimalType = "Dog",
                            MaleFemale = "Unknown"
                        },
                        new
                        {
                            AnimalId = 4,
                            AnimalAge = 18,
                            AnimalDescription = "Big Gwyneth Paltrow fan.",
                            AnimalName = "Womb",
                            AnimalType = "Dog",
                            MaleFemale = "Female"
                        },
                        new
                        {
                            AnimalId = 5,
                            AnimalAge = 2,
                            AnimalDescription = "While he may be new to the fashion scene, he's known what he's wanted to do his whole life. Style you in the best outfits he can.",
                            AnimalName = "Jimmy Chew",
                            AnimalType = "Dog",
                            MaleFemale = "Male"
                        },
                        new
                        {
                            AnimalId = 6,
                            AnimalAge = 5,
                            AnimalDescription = "They think their a lot tougher than they are. Spicy outside, soft inside",
                            AnimalName = "Wasabi",
                            AnimalType = "Cat",
                            MaleFemale = "Male"
                        },
                        new
                        {
                            AnimalId = 7,
                            AnimalAge = 1,
                            AnimalDescription = "Was seen fraternizing with racoons. Bullied by other cats now.",
                            AnimalName = "Racoon",
                            AnimalType = "Cat",
                            MaleFemale = "Male"
                        },
                        new
                        {
                            AnimalId = 8,
                            AnimalAge = 314,
                            AnimalDescription = "Can rattle off over 300 variables from the Pi sequence and very proud of it.",
                            AnimalName = "Pi",
                            AnimalType = "Cat",
                            MaleFemale = "Female"
                        },
                        new
                        {
                            AnimalId = 9,
                            AnimalAge = 6,
                            AnimalDescription = "Hacked into the CIA. We can't talk about it.",
                            AnimalName = "Linux",
                            AnimalType = "Cat",
                            MaleFemale = "Female"
                        },
                        new
                        {
                            AnimalId = 10,
                            AnimalAge = 1,
                            AnimalDescription = "They are a tuxedo cat and believes that makes them better than everyone else, since they are always best dressed.",
                            AnimalName = "Richard",
                            AnimalType = "Cat",
                            MaleFemale = "Male"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
